<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1670982561111" stop="1670982602061" version="1.4.0">
    <name>All Test Suite</name>
    <test-cases>
        <test-case start="1670982561182" stop="1670982570787" status="passed">
            <name>initailDemo1</name>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
        <test-case start="1670982570899" stop="1670982574959" status="passed">
            <name>initialDemo2</name>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
        <test-case start="1670982574962" stop="1670982584154" status="passed">
            <name>initialDemo3</name>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
        <test-case start="1670982584157" stop="1670982600866" status="failed">
            <name>Date</name>
            <failure>
                <message>AssertionError: expected [https://rahulshettyacademy.com/dropdownsPractise/] but found [this is test]</message>
                <stack-trace>java.lang.AssertionError: expected [https://rahulshettyacademy.com/dropdownsPractise/] but found [this is test]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotSame(Assert.java:508)
	at org.testng.Assert.assertSame(Assert.java:459)
	at org.testng.Assert.assertSame(Assert.java:469)
	at myExtendReportPackage.Test4.Date(Test4.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="feature" value="Test"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
